export const sampleData = {
  genres: [
    { name: "Fantasy" },
    { name: "Science Fiction" },
    { name: "Mystery" },
    { name: "Thriller" },
    { name: "Romance" },
    { name: "Historical Fiction" },
    { name: "Horror" },
    { name: "Young Adult" },
    { name: "Children’s" },
    { name: "Adventure" },
    { name: "Dystopian" },
    { name: "Contemporary" },
    { name: "Literary Fiction" },
    { name: "Graphic Novel" },
    { name: "Crime" },
    { name: "Poetry" },
    { name: "Biography" },
    { name: "Autobiography" },
    { name: "Memoir" },
    { name: "Self-Help" },
    { name: "History" },
    { name: "Science" },
    { name: "Philosophy" },
    { name: "Psychology" },
    { name: "Spirituality" },
    { name: "Business" },
    { name: "Economics" },
    { name: "Politics" },
    { name: "Art & Photography" },
    { name: "Cookbook" },
    { name: "Travel" },
    { name: "True Crime" },
    { name: "Health & Fitness" },
    { name: "Education" },
    { name: "Technology" },
    { name: "Short Stories" },
    { name: "Classic Literature" },
    { name: "Comics & Manga" },
  ],
};
